redmine/config/routes.rb
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

Rails.application.routes.draw do
  root :to => 'welcome#index', :as => 'home'

  match 'login', :to => 'account#login', :as => 'signin', :via => [:get, :post]
  match 'logout', :to => 'account#logout', :as => 'signout', :via => [:get, :post]
  match 'account/register', :to => 'account#register', :via => [:get, :post], :as => 'register'
  match 'account/lost_password', :to => 'account#lost_password', :via => [:get, :post], :as => 'lost_password'
  match 'account/activate', :to => 'account#activate', :via => :get
  get 'account/activation_email', :to => 'account#activation_email', :as => 'activation_email'

  match '/news/preview', :controller => 'previews', :action => 'news', :as => 'preview_news', :via => [:get, :post, :put, :patch]
  match '/issues/preview/new/:project_id', :to => 'previews#issue', :as => 'preview_new_issue', :via => [:get, :post, :put, :patch]
  match '/issues/preview/edit/:id', :to => 'previews#issue', :as => 'preview_edit_issue', :via => [:get, :post, :put, :patch]
  match '/issues/preview', :to => 'previews#issue', :as => 'preview_issue', :via => [:get, :post, :put, :patch]

  match 'projects/:id/wiki', :to => 'wikis#edit', :via => :post
  match 'projects/:id/wiki/destroy', :to => 'wikis#destroy', :via => [:get, :post]

  match 'boards/:board_id/topics/new', :to => 'messages#new', :via => [:get, :post], :as => 'new_board_message'
  get 'boards/:board_id/topics/:id', :to => 'messages#show', :as => 'board_message'
  match 'boards/:board_id/topics/quote/:id', :to => 'messages#quote', :via => [:get, :post]
  get 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'

  post 'boards/:board_id/topics/preview', :to => 'messages#preview', :as => 'preview_board_message'
  post 'boards/:board_id/topics/:id/replies', :to => 'messages#reply'
  post 'boards/:board_id/topics/:id/edit', :to => 'messages#edit'
  post 'boards/:board_id/topics/:id/destroy', :to => 'messages#destroy'

  # Misc issue routes. TODO: move into resources
  match '/issues/auto_complete', :to => 'auto_completes#issues', :via => :get, :as => 'auto_complete_issues'
  match '/issues/context_menu', :to => 'context_menus#issues', :as => 'issues_context_menu', :via => [:get, :post]
  match '/issues/changes', :to => 'journals#index', :as => 'issue_changes', :via => :get
  match '/issues/:id/quoted', :to => 'journals#new', :id => /\d+/, :via => :post, :as => 'quoted_issue'

  match '/journals/diff/:id', :to => 'journals#diff', :id => /\d+/, :via => :get
  match '/journals/edit/:id', :to => 'journals#edit', :id => /\d+/, :via => [:get, :post]

  get '/projects/:project_id/issues/gantt', :to => 'gantts#show', :as => 'project_gantt'
  get '/issues/gantt', :to => 'gantts#show'

  get '/projects/:project_id/issues/calendar', :to => 'calendars#show', :as => 'project_calendar'
  get '/issues/calendar', :to => 'calendars#show'

  get 'projects/:id/issues/report', :to => 'reports#issue_report', :as => 'project_issues_report'
  get 'projects/:id/issues/report/:detail', :to => 'reports#issue_report_details', :as => 'project_issues_report_details'

  get   '/issues/imports/new', :to => 'imports#new', :as => 'new_issues_import'
  post  '/imports', :to => 'imports#create', :as => 'imports'
  get   '/imports/:id', :to => 'imports#show', :as => 'import'
  match '/imports/:id/settings', :to => 'imports#settings', :via => [:get, :post], :as => 'import_settings'
  match '/imports/:id/mapping', :to => 'imports#mapping', :via => [:get, :post], :as => 'import_mapping'
  match '/imports/:id/run', :to => 'imports#run', :via => [:get, :post], :as => 'import_run'

  match 'my/account', :controller => 'my', :action => 'account', :via => [:get, :post]
  match 'my/account/destroy', :controller => 'my', :action => 'destroy', :via => [:get, :post]
  match 'my/page', :controller => 'my', :action => 'page', :via => :get
  match 'my', :controller => 'my', :action => 'index', :via => :get # Redirects to my/page
  get 'my/api_key', :to => 'my#show_api_key', :as => 'my_api_key'
  post 'my/api_key', :to => 'my#reset_api_key'
  post 'my/rss_key', :to => 'my#reset_rss_key', :as => 'my_rss_key'
  match 'my/password', :controller => 'my', :action => 'password', :via => [:get, :post]
  match 'my/page_layout', :controller => 'my', :action => 'page_layout', :via => :get
  match 'my/add_block', :controller => 'my', :action => 'add_block', :via => :post
  match 'my/remove_block', :controller => 'my', :action => 'remove_block', :via => :post
  match 'my/order_blocks', :controller => 'my', :action => 'order_blocks', :via => :post

  resources :users do
    resources :memberships, :controller => 'principal_memberships'
    resources :email_addresses, :only => [:index, :create, :update, :destroy]
  end

  post 'watchers/watch', :to => 'watchers#watch', :as => 'watch'
  delete 'watchers/watch', :to => 'watchers#unwatch'
  get 'watchers/new', :to => 'watchers#new'
  post 'watchers', :to => 'watchers#create'
  post 'watchers/append', :to => 'watchers#append'
  delete 'watchers', :to => 'watchers#destroy'
  get 'watchers/autocomplete_for_user', :to => 'watchers#autocomplete_for_user'
  # Specific routes for issue watchers API
  post 'issues/:object_id/watchers', :to => 'watchers#create', :object_type => 'issue'
  delete 'issues/:object_id/watchers/:user_id' => 'watchers#destroy', :object_type => 'issue'

  resources :projects do
    member do
      get 'settings(/:tab)', :action => 'settings', :as => 'settings'
      post 'modules'
      post 'archive'
      post 'unarchive'
      post 'close'
      post 'reopen'
      match 'copy', :via => [:get, :post]
    end

    shallow do
      resources :memberships, :controller => 'members', :only => [:index, :show, :new, :create, :update, :destroy] do
        collection do
          get 'autocomplete'
        end
      end
    end

    resource :enumerations, :controller => 'project_enumerations', :only => [:update, :destroy]

    get 'issues/:copy_from/copy', :to => 'issues#new', :as => 'copy_issue'
    resources :issues, :only => [:index, :new, :create]
    # Used when updating the form of a new issue
    post 'issues/new', :to => 'issues#new'

    resources :files, :only => [:index, :new, :create]

    resources :versions, :except => [:index, :show, :edit, :update, :destroy] do
      collection do
        put 'close_completed'
      end
    end
    get 'versions.:format', :to => 'versions#index'
    get 'roadmap', :to => 'versions#index', :format => false
    get 'versions', :to => 'versions#index'

    resources :news, :except => [:show, :edit, :update, :destroy]
    resources :time_entries, :controller => 'timelog', :except => [:show, :edit, :update, :destroy] do
      get 'report', :on => :collection
    end
    resources :queries, :only => [:new, :create]
    shallow do
      resources :issue_categories
    end
    resources :documents, :except => [:show, :edit, :update, :destroy]
    resources :boards
    shallow do
      resources :repositories, :except => [:index, :show] do
        member do
          match 'committers', :via => [:get, :post]
        end
      end
    end
  
    match 'wiki/index', :controller => 'wiki', :action => 'index', :via => :get
    resources :wiki, :except => [:index, :new, :create], :as => 'wiki_page' do
      member do
        get 'rename'
        post 'rename'
        get 'history'
        get 'diff'
        match 'preview', :via => [:post, :put, :patch]
        post 'protect'
        post 'add_attachment'
      end
      collection do
        get 'export'
        get 'date_index'
      end
    end
    match 'wiki', :controller => 'wiki', :action => 'show', :via => :get
    get 'wiki/:id/:version', :to => 'wiki#show', :constraints => {:version => /\d+/}
    delete 'wiki/:id/:version', :to => 'wiki#destroy_version'
    get 'wiki/:id/:version/annotate', :to => 'wiki#annotate'
    get 'wiki/:id/:version/diff', :to => 'wiki#diff'
  end

  resources :issues do
    member do
      # Used when updating the form of an existing issue
      patch 'edit', :to => 'issues#edit'
    end
    collection do
      match 'bulk_edit', :via => [:get, :post]
      post 'bulk_update'
    end
    resources :time_entries, :controller => 'timelog', :except => [:show, :edit, :update, :destroy] do
      collection do
        get 'report'
      end
    end
    shallow do
      resources :relations, :controller => 'issue_relations', :only => [:index, :show, :create, :destroy]
    end
  end
  # Used when updating the form of a new issue outside a project
  post '/issues/new', :to => 'issues#new'
  match '/issues', :controller => 'issues', :action => 'destroy', :via => :delete

  resources :queries, :except => [:show]

  resources :news, :only => [:index, :show, :edit, :update, :destroy]
  match '/news/:id/comments', :to => 'comments#create', :via => :post
  match '/news/:id/comments/:comment_id', :to => 'comments#destroy', :via => :delete

  resources :versions, :only => [:show, :edit, :update, :destroy] do
    post 'status_by', :on => :member
  end

  resources :documents, :only => [:show, :edit, :update, :destroy] do
    post 'add_attachment', :on => :member
  end

  match '/time_entries/context_menu', :to => 'context_menus#time_entries', :as => :time_entries_context_menu, :via => [:get, :post]

  resources :time_entries, :controller => 'timelog', :except => :destroy do
    collection do
      get 'report'
      get 'bulk_edit'
      post 'bulk_update'
    end
  end
  match '/time_entries/:id', :to => 'timelog#destroy', :via => :delete, :id => /\d+/
  # TODO: delete /time_entries for bulk deletion
  match '/time_entries/destroy', :to => 'timelog#destroy', :via => :delete
  # Used to update the new time entry form
  post '/time_entries/new', :to => 'timelog#new'

redmine/app/controllers/imports_controller.rb
# Redmine - project management software
# Copyright (C) 2006-2016  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

require 'csv'

class ImportsController < ApplicationController

  before_filter :find_import, :only => [:show, :settings, :mapping, :run]
  before_filter :authorize_global

  helper :issues

  def new
  end

  def create
    @import = IssueImport.new
    @import.user = User.current
    @import.file = params[:file]
    @import.set_default_settings

    if @import.save
      redirect_to import_settings_path(@import)
    else
      render :action => 'new'
    end
  end

  def show
  end

  def settings
    if request.post? && @import.parse_file
      redirect_to import_mapping_path(@import)
    end

  rescue CSV::MalformedCSVError => e
    flash.now[:error] = l(:error_invalid_csv_file_or_settings)
  rescue ArgumentError, EncodingError => e
    flash.now[:error] = l(:error_invalid_file_encoding, :encoding => ERB::Util.h(@import.settings['encoding']))
  rescue SystemCallError => e
    flash.now[:error] = l(:error_can_not_read_import_file)
  end

  def mapping
    issue = Issue.new
    issue.project = @import.project
    issue.tracker = @import.tracker
    @attributes = issue.safe_attribute_names
    @custom_fields = issue.editable_custom_field_values.map(&:custom_field)

    if request.post?
      respond_to do |format|
        format.html {
          if params[:previous]
            redirect_to import_settings_path(@import)
          else
            redirect_to import_run_path(@import)
          end
        }
        format.js # updates mapping form on project or tracker change
      end
    end
  end

  def run
    if request.post?
      @current = @import.run(
        :max_items => max_items_per_request,
        :max_time => 10.seconds
      )
      respond_to do |format|
        format.html {
          if @import.finished?
            redirect_to import_path(@import)
          else
            redirect_to import_run_path(@import)
          end
        }
        format.js
      end
    end
  end

  private

  def find_import
    @import = Import.where(:user_id => User.current.id, :filename => params[:id]).first
    if @import.nil?
      render_404
      return
    elsif @import.finished? && action_name != 'show'
      redirect_to import_path(@import)
      return
    end
    update_from_params if request.post?
  end

  def update_from_params
    if params[:import_settings].is_a?(Hash)
      @import.settings ||= {}
      @import.settings.merge!(params[:import_settings])
      @import.save!
    end
  end

  def max_items_per_request
    5
  end
end

redmine/app/helpers/imports_helper.rb
# encoding: utf-8
#
# Redmine - project management software
# Copyright (C) 2006-2016  Jean-Philippe Lang
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.

module ImportsHelper
  def options_for_mapping_select(import, field, options={})
    tags = "".html_safe
    blank_text = options[:required] ? "-- #{l(:actionview_instancetag_blank_option)} --" : "&nbsp;".html_safe
    tags << content_tag('option', blank_text, :value => '')
    tags << options_for_select(import.columns_options, import.mapping[field])
    tags
  end

  def mapping_select_tag(import, field, options={})
    name = "import_settings[mapping][#{field}]"
    select_tag name, options_for_mapping_select(import, field, options)
  end

  # Returns the options for the date_format setting
  def date_format_options
    Import::DATE_FORMATS.map do |f|
      format = f.gsub('%', '').gsub(/[dmY]/) do
        {'d' => 'DD', 'm' => 'MM', 'Y' => 'YYYY'}[$&]
      end
      [format, f]
    end
  end
end

redmine/app/views/imports/_fields_mapping.html.erb
<div class="splitcontent">
<div class="splitcontentleft">
<p>
  <label><%= l(:label_project) %></label>
  <%= select_tag 'import_settings[mapping][project_id]',
        options_for_select(project_tree_options_for_select(@import.allowed_target_projects, :selected => @import.project)),
        :id => 'issue_project_id' %>
</p>
<p>
  <label><%= l(:label_tracker) %></label>
  <%= select_tag 'import_settings[mapping][tracker_id]',
        options_for_select(@import.allowed_target_trackers.sorted.map {|t| [t.name, t.id]}, @import.tracker.try(:id)),
        :id => 'issue_tracker_id' %>
</p>
<p>
  <label><%= l(:field_subject) %></label>
  <%= mapping_select_tag @import, 'subject', :required => true %>
</p>
<p>
  <label><%= l(:field_description) %></label>
  <%= mapping_select_tag @import, 'description' %>
</p>
<p>
  <label><%= l(:field_priority) %></label>
  <%= mapping_select_tag @import, 'priority' %>
</p>
<p>
  <label><%= l(:field_category) %></label>
  <%= mapping_select_tag @import, 'category' %>
  <% if User.current.allowed_to?(:manage_categories, @import.project) %>
    <label class="block">
      <%= check_box_tag 'import_settings[mapping][create_categories]', '1', @import.create_categories? %>
      <%= l(:label_create_missing_values) %>
    </label>
  <% end %>
</p>
<p>
  <label><%= l(:field_assigned_to) %></label>
  <%= mapping_select_tag @import, 'assigned_to' %>
</p>
<p>
  <label><%= l(:field_fixed_version) %></label>
  <%= mapping_select_tag @import, 'fixed_version' %>
  <% if User.current.allowed_to?(:manage_versions, @import.project) %>
    <label class="block">
      <%= check_box_tag 'import_settings[mapping][create_versions]', '1', @import.create_versions? %>
      <%= l(:label_create_missing_values) %>
    </label>
  <% end %>
</p>
<% @custom_fields.each do |field| %>
  <p>
    <label><%= field.name %></label>
    <%= mapping_select_tag @import, "cf_#{field.id}" %>
  </p>
<% end %>
</div>

<div class="splitcontentright">
<p>
  <label><%= l(:field_is_private) %></label>
  <%= mapping_select_tag @import, 'is_private' %>
</p>
<p>
  <label><%= l(:field_parent_issue) %></label>
  <%= mapping_select_tag @import, 'parent_issue_id' %>
</p>
<p>
  <label><%= l(:field_start_date) %></label>
  <%= mapping_select_tag @import, 'start_date' %>
</p>
<p>
  <label><%= l(:field_due_date) %></label>
  <%= mapping_select_tag @import, 'due_date' %>
</p>
<p>
  <label><%= l(:field_estimated_hours) %></label>
  <%= mapping_select_tag @import, 'estimated_hours' %>
</p>
<p>
  <label><%= l(:field_done_ratio) %></label>
  <%= mapping_select_tag @import, 'done_ratio' %>
</p>
</div>
</div>

redmine/app/views/imports/mapping.html.erb
<h2><%= l(:label_import_issues) %></h2>

<%= form_tag(import_mapping_path(@import), :id => "import-form") do %>
  <fieldset class="box tabular">
    <legend><%= l(:label_fields_mapping) %></legend>
    <div id="fields-mapping">
      <%= render :partial => 'fields_mapping' %>
    </div>
  </fieldset>

  <div class="autoscroll">
  <fieldset class="box">
    <legend><%= l(:label_file_content_preview) %></legend>

      <table class="sample-data">
      <% @import.first_rows.each do |row| %>
        <tr>
          <%= row.map {|c| content_tag 'td', truncate(c.to_s, :length => 50) }.join("").html_safe %>
        </tr>
      <% end %>
      </table>
  </fieldset>
  </div>

  <p>
    <%= button_tag("\xc2\xab " + l(:label_previous), :name => 'previous') %>
    <%= submit_tag l(:button_import) %>
  </p>
<% end %>

<% content_for :sidebar do %>
    <%= render :partial => 'issues/sidebar' %>
<% end %>


<%= javascript_tag do %>
$(document).ready(function() {
  $('#fields-mapping').on('change', '#issue_project_id, #issue_tracker_id', function(){
    $.ajax({
      url: '<%= import_mapping_path(@import, :format => 'js') %>',
      type: 'post',
      data: $('#import-form').serialize()
    });
  });

  $('#import-form').submit(function(){
    $('#import-details').show().addClass('ajax-loading');
    $('#import-progress').progressbar({value: 0, max: <%= @import.total_items || 0 %>});
  });

});
<% end %>

redmine/app/views/imports/mapping.js.erb
$('#fields-mapping').html('<%= escape_javascript(render :partial => 'fields_mapping') %>');

redmine/app/views/imports/new.html.erb
<h2><%= l(:label_import_issues) %></h2>

<%= form_tag(imports_path, :multipart => true) do %>
  <fieldset class="box">
    <legend><%= l(:label_select_file_to_import) %> (CSV)</legend>
    <p>
      <%= file_field_tag 'file' %>
    </p>
  </fieldset>
  <p><%= submit_tag l(:label_next).html_safe + " &#187;".html_safe, :name => nil %></p>
<% end %>

<% content_for :sidebar do %>
    <%= render :partial => 'issues/sidebar' %>
<% end %>

redmine/app/views/imports/run.html.erb
<h2><%= l(:label_import_issues) %></h2>

<div id="import-details">
  <div id="import-progress"><div id="progress-label">0 / <%= @import.total_items.to_i %></div></div>
</div>

<% content_for :sidebar do %>
  <%= render :partial => 'issues/sidebar' %>
<% end %>

<%= javascript_tag do %>
$(document).ready(function() {
  $('#import-details').addClass('ajax-loading');
  $('#import-progress').progressbar({value: 0, max: <%= @import.total_items.to_i %>});
  $.ajax({
    url: '<%= import_run_path(@import, :format => 'js') %>',
    type: 'post'
  });
});
<% end %>

redmine/app/views/imports/run.js.erb
$('#import-progress').progressbar({value: <%= @current.to_i %>});
$('#progress-label').text("<%= @current.to_i %> / <%= @import.total_items.to_i %>");

<% if @import.finished? %>
window.location.href='<%= import_path(@import) %>';
<% else %>
$.ajax({
  url: '<%= import_run_path(@import, :format => 'js') %>',
  type: 'post'
});
<% end %>

redmine/app/views/imports/settings.html.erb
<h2><%= l(:label_import_issues) %></h2>

<%= form_tag(import_settings_path(@import), :id => "import-form") do %>
  <fieldset class="box tabular">
    <legend><%= l(:label_options) %></legend>
    <p>
      <label><%= l(:label_fields_separator) %></label>
      <%= select_tag 'import_settings[separator]',
            options_for_select([[l(:label_comma_char), ','], [l(:label_semi_colon_char), ';']], @import.settings['separator']) %>
    </p>
    <p>
      <label><%= l(:label_fields_wrapper) %></label>
      <%= select_tag 'import_settings[wrapper]',
          options_for_select([[l(:label_quote_char), "'"], [l(:label_double_quote_char), '"']], @import.settings['wrapper']) %>
    </p>
    <p>
      <label><%= l(:label_encoding) %></label>
      <%= select_tag 'import_settings[encoding]', options_for_select(Setting::ENCODINGS, @import.settings['encoding']) %>
    </p>
    <p>
      <label><%= l(:setting_date_format) %></label>
      <%= select_tag 'import_settings[date_format]', options_for_select(date_format_options, @import.settings['date_format']) %>
    </p>
  </fieldset>
  <p><%= submit_tag l(:label_next).html_safe + " &#187;".html_safe, :name => nil %></p>
<% end %>

<% content_for :sidebar do %>
    <%= render :partial => 'issues/sidebar' %>
<% end %>

redmine/app/views/imports/show.html.erb
<h2><%= l(:label_import_issues) %></h2>

<% if @import.unsaved_items.count == 0 %>
  <p><%= l(:notice_import_finished, :count => @import.saved_items.count) %></p>

  <ul>
  <% @import.saved_objects.each do |issue| %>
    <li><%= link_to_issue issue %></li>
  <% end %>
  </ul>
<% else %>
  <p><%= l(:notice_import_finished_with_errors, :count => @import.unsaved_items.count, :total => @import.total_items) %></p>

  <table id="unsaved-items" class="list">
    <tr>
      <th>Position</th>
      <th>Message</th>
    </tr>
  <% @import.unsaved_items.each do |item| %>
    <tr>
      <td><%= item.position %></td>
      <td><%= simple_format_without_paragraph item.message %></td>
    </tr>
  <% end %>
  </table>
<% end %>

<% content_for :sidebar do %>
    <%= render :partial => 'issues/sidebar' %>
<% end %>